# Generated by Django 4.0 on 2022-02-03 20:07

from django.db import migrations, models
import django.db.models.deletion
import gallery_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0008_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=200)),
                ('gallery_category', models.CharField(choices=[('animal', 'ANIMAL'), ('music', 'MUSIC'), ('cinema', 'CINEMA'), ('abstract', 'ABSTRACT'), ('architecture', 'ARCHITECTURE'), ('colletibles', 'COLLECTIBLES'), ('utility', 'UTILITY'), ('photography', 'PHOTOGRAPHY'), ('virtual-world', 'VIRTUAL-WORLD'), ('various', 'VARIOUS')], default='various', max_length=20)),
                ('public_gallery', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newgallery', to='users_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='NewNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFT_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=gallery_app.models.get_upload_path)),
                ('caption', models.CharField(max_length=3000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('link', models.URLField(max_length=300)),
                ('contract_address', models.CharField(max_length=300)),
                ('token_id', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newnft', to='gallery_app.newgallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernft', to='users_app.user')),
            ],
        ),
    ]
