# Generated by Django 4.0 on 2022-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgallery',
            name='wallett_address',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
