# Generated by Django 4.0 on 2022-02-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_newgallery_wallett_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgallery',
            name='wallett_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
