# Generated by Django 4.0 on 2022-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_newgallery_wallett_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgallery',
            name='gallery_category',
            field=models.CharField(choices=[('animal', 'ANIMAL'), ('music', 'MUSIC'), ('cinema', 'CINEMA'), ('abstract', 'ABSTRACT'), ('architecture', 'ARCHITECTURE'), ('colletibles', 'COLLECTIBLES'), ('utility', 'UTILITY'), ('photography', 'PHOTOGRAPHY'), ('virtual-world', 'VIRTUAL-WORLD'), ('various', 'VARIOUS')], default='animal', max_length=20),
        ),
    ]
