# Generated by Django 4.0 on 2022-02-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_alter_newgallery_gallery_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newnft',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='newnft',
            name='price',
        ),
    ]
