# Generated by Django 4.0 on 2022-02-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_rename_caption_newnft_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newnft',
            old_name='NFT_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='newnft',
            name='token_id',
        ),
    ]
