# Generated by Django 4.0 on 2022-02-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_rename_nft_name_newnft_name_remove_newnft_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnft',
            name='nft_created_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
