# Generated by Django 4.0 on 2022-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0007_newnft_nft_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnft',
            name='description',
            field=models.CharField(default='No description provided', max_length=3000),
        ),
    ]
