# Generated by Django 4.0 on 2022-02-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0008_alter_newnft_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnft',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
