# Generated by Django 4.0 on 2022-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0009_alter_newnft_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgallery',
            name='gallery_name',
            field=models.CharField(max_length=35),
        ),
    ]
