# Generated by Django 4.0 on 2022-02-16 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery_app', '0011_alter_newgallery_gallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgallery',
            name='gallery_like',
            field=models.ManyToManyField(blank=True, related_name='liked_gallery', to=settings.AUTH_USER_MODEL),
        ),
    ]
