# Generated by Django 4.0 on 2022-02-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0009_alter_user_avatar'),
        ('gallery_app', '0012_newgallery_gallery_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgallery',
            name='gallery_like',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_gallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=10)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.newgallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
        ),
    ]
