# Generated by Django 4.0 on 2022-02-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0013_alter_newgallery_gallery_like_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
