# Generated by Django 4.0 on 2022-01-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_blog_name',
        ),
    ]
