# Generated by Django 4.0 on 2022-02-14 16:53

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatars/nftexample.png', upload_to=users_app.models.get_upload_path),
        ),
    ]
